### ISSUE TITLE
get connected ip's

### ISSUE THREAD

**Issue by mostafa9112** [alirezax5/xuiapi#3]
hi alireza can you add get connected ip's on next update?

i can use this panels. supported?
https://github.com/MHSanaei/3x-ui
niduka
asadi

**Comment by alirezax5** [comment]
> hi alireza can you add get connected ip's on next update?
> 
> i can use this panels. supported? https://github.com/MHSanaei/3x-ui niduka asadi


 Hello, this script enters the panel like a real user and sends a request

 That's why you can't get the IPs except to install a webserver and get the IPs according to the mechanism of the developer


 This script supports 99% panels and by default I put 4 panels that you can
 https://github.com/alirezax5/xuiapi/tree/main/src/Panel
 look
